name: Test

on:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Get Go version
      run: |
        echo "GO_VER=`go list -m -f={{.GoVersion}}`" >> $GITHUB_ENV 

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VER }}
        cache-dependency-path: go.sum

    - name: Get dependencies
      run: go get .

    - name: Test
      run: go test -v ./... 
  
